#pragma once

#include "Adafruit_GFX/Adafruit_GFX.hpp"

#define ACCENT_COLOR ILI9341_OLIVE
#define ACCENT_BLOCKED_COLOR ILI9341_GREEN
#define BACKGROUND_COLOR ILI9341_DARKGREY
#define FOREGROUND_COLOR ILI9341_DARKRED
#define TEXT_COLOR ILI9341_WHITE
#define SEPARATOR_COLOR ILI9341_LIGHTGREY
