/*
 * printf_config.h
 *
 *  Created on: May 6, 2025
 *      Author: Maktub
 */

#ifndef CORE_INC_PRINTF_CONFIG_H_
#define CORE_INC_PRINTF_CONFIG_H_

#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
//#define PRINTF_DISABLE_SUPPORT_FLOAT

#endif /* CORE_INC_PRINTF_CONFIG_H_ */
